<?php
/**
 * AutobahnClosure automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class AutobahnClosure implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $id = null;
    protected ?bool $blocked = null;
    protected ?bool $future = null;
    protected ?string $title = null;
    protected ?string $subtitle = null;
    /**
     * @var array<string>|null
     */
    protected ?array $description = null;
    protected ?\PSX\DateTime\LocalDateTime $startDate = null;
    protected ?AutobahnCoordinate $coordinate = null;
    /**
     * @var array<AutobahnCoordinate>|null
     */
    protected ?array $lineString = null;
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setBlocked(?bool $blocked): void
    {
        $this->blocked = $blocked;
    }
    public function getBlocked(): ?bool
    {
        return $this->blocked;
    }
    public function setFuture(?bool $future): void
    {
        $this->future = $future;
    }
    public function getFuture(): ?bool
    {
        return $this->future;
    }
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }
    public function getTitle(): ?string
    {
        return $this->title;
    }
    public function setSubtitle(?string $subtitle): void
    {
        $this->subtitle = $subtitle;
    }
    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }
    /**
     * @param array<string>|null $description
     */
    public function setDescription(?array $description): void
    {
        $this->description = $description;
    }
    /**
     * @return array<string>|null
     */
    public function getDescription(): ?array
    {
        return $this->description;
    }
    public function setStartDate(?\PSX\DateTime\LocalDateTime $startDate): void
    {
        $this->startDate = $startDate;
    }
    public function getStartDate(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->startDate;
    }
    public function setCoordinate(?AutobahnCoordinate $coordinate): void
    {
        $this->coordinate = $coordinate;
    }
    public function getCoordinate(): ?AutobahnCoordinate
    {
        return $this->coordinate;
    }
    /**
     * @param array<AutobahnCoordinate>|null $lineString
     */
    public function setLineString(?array $lineString): void
    {
        $this->lineString = $lineString;
    }
    /**
     * @return array<AutobahnCoordinate>|null
     */
    public function getLineString(): ?array
    {
        return $this->lineString;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('blocked', $this->blocked);
        $record->put('future', $this->future);
        $record->put('title', $this->title);
        $record->put('subtitle', $this->subtitle);
        $record->put('description', $this->description);
        $record->put('startDate', $this->startDate);
        $record->put('coordinate', $this->coordinate);
        $record->put('lineString', $this->lineString);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
