<?php
/**
 * AutobahnParkingLorry automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class AutobahnParkingLorry implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $id = null;
    protected ?string $title = null;
    protected ?string $subtitle = null;
    /**
     * @var array<string>|null
     */
    protected ?array $description = null;
    protected ?AutobahnCoordinate $coordinate = null;
    /**
     * @var array<string>|null
     */
    protected ?array $features = null;
    public function setId(?string $id) : void
    {
        $this->id = $id;
    }
    public function getId() : ?string
    {
        return $this->id;
    }
    public function setTitle(?string $title) : void
    {
        $this->title = $title;
    }
    public function getTitle() : ?string
    {
        return $this->title;
    }
    public function setSubtitle(?string $subtitle) : void
    {
        $this->subtitle = $subtitle;
    }
    public function getSubtitle() : ?string
    {
        return $this->subtitle;
    }
    /**
     * @param array<string>|null $description
     */
    public function setDescription(?array $description) : void
    {
        $this->description = $description;
    }
    /**
     * @return array<string>|null
     */
    public function getDescription() : ?array
    {
        return $this->description;
    }
    public function setCoordinate(?AutobahnCoordinate $coordinate) : void
    {
        $this->coordinate = $coordinate;
    }
    public function getCoordinate() : ?AutobahnCoordinate
    {
        return $this->coordinate;
    }
    /**
     * @param array<string>|null $features
     */
    public function setFeatures(?array $features) : void
    {
        $this->features = $features;
    }
    /**
     * @return array<string>|null
     */
    public function getFeatures() : ?array
    {
        return $this->features;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('title', $this->title);
        $record->put('subtitle', $this->subtitle);
        $record->put('description', $this->description);
        $record->put('coordinate', $this->coordinate);
        $record->put('features', $this->features);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
