<?php
/**
 * Budget automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class Budget implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $id = null;
    protected ?string $label = null;
    protected ?int $value = null;
    protected ?int $relativeToParentValue = null;
    protected ?int $relativeValue = null;
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setLabel(?string $label): void
    {
        $this->label = $label;
    }
    public function getLabel(): ?string
    {
        return $this->label;
    }
    public function setValue(?int $value): void
    {
        $this->value = $value;
    }
    public function getValue(): ?int
    {
        return $this->value;
    }
    public function setRelativeToParentValue(?int $relativeToParentValue): void
    {
        $this->relativeToParentValue = $relativeToParentValue;
    }
    public function getRelativeToParentValue(): ?int
    {
        return $this->relativeToParentValue;
    }
    public function setRelativeValue(?int $relativeValue): void
    {
        $this->relativeValue = $relativeValue;
    }
    public function getRelativeValue(): ?int
    {
        return $this->relativeValue;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('label', $this->label);
        $record->put('value', $this->value);
        $record->put('relativeToParentValue', $this->relativeToParentValue);
        $record->put('relativeValue', $this->relativeValue);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
