<?php
/**
 * BudgetTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\Payload;
use Sdkgen\Client\Exception\UnknownStatusCodeException;
use Sdkgen\Client\TagAbstract;

class BudgetTag extends TagAbstract
{
    public function expense(): BudgetExpenseTag
    {
        return new BudgetExpenseTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function income(): BudgetIncomeTag
    {
        return new BudgetIncomeTag(
            $this->httpClient,
            $this->parser
        );
    }


}
