<?php
/**
 * BundestagTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\UnknownStatusCodeException;
use Sdkgen\Client\TagAbstract;

class BundestagTag extends TagAbstract
{
    public function member(): BundestagMemberTag
    {
        return new BundestagMemberTag(
            $this->httpClient,
            $this->parser
        );
    }


}
