<?php
/**
 * BundestagConstituency automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class BundestagConstituency implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $number = null;
    protected ?string $name = null;
    public function setNumber(?string $number): void
    {
        $this->number = $number;
    }
    public function getNumber(): ?string
    {
        return $this->number;
    }
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('number', $this->number);
        $record->put('name', $this->name);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
