<?php
/**
 * BundestagMember automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class BundestagMember implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $id = null;
    protected ?string $name = null;
    protected ?string $party = null;
    protected ?string $bioUrl = null;
    protected ?string $state = null;
    protected ?BundestagConstituency $constituency = null;
    protected ?string $elected = null;
    protected ?string $photo = null;
    protected ?string $photoLarge = null;
    protected ?\PSX\DateTime\LocalDateTime $photoLastChanged = null;
    protected ?\PSX\DateTime\LocalDateTime $lastChanged = null;
    public function setId(?string $id) : void
    {
        $this->id = $id;
    }
    public function getId() : ?string
    {
        return $this->id;
    }
    public function setName(?string $name) : void
    {
        $this->name = $name;
    }
    public function getName() : ?string
    {
        return $this->name;
    }
    public function setParty(?string $party) : void
    {
        $this->party = $party;
    }
    public function getParty() : ?string
    {
        return $this->party;
    }
    public function setBioUrl(?string $bioUrl) : void
    {
        $this->bioUrl = $bioUrl;
    }
    public function getBioUrl() : ?string
    {
        return $this->bioUrl;
    }
    public function setState(?string $state) : void
    {
        $this->state = $state;
    }
    public function getState() : ?string
    {
        return $this->state;
    }
    public function setConstituency(?BundestagConstituency $constituency) : void
    {
        $this->constituency = $constituency;
    }
    public function getConstituency() : ?BundestagConstituency
    {
        return $this->constituency;
    }
    public function setElected(?string $elected) : void
    {
        $this->elected = $elected;
    }
    public function getElected() : ?string
    {
        return $this->elected;
    }
    public function setPhoto(?string $photo) : void
    {
        $this->photo = $photo;
    }
    public function getPhoto() : ?string
    {
        return $this->photo;
    }
    public function setPhotoLarge(?string $photoLarge) : void
    {
        $this->photoLarge = $photoLarge;
    }
    public function getPhotoLarge() : ?string
    {
        return $this->photoLarge;
    }
    public function setPhotoLastChanged(?\PSX\DateTime\LocalDateTime $photoLastChanged) : void
    {
        $this->photoLastChanged = $photoLastChanged;
    }
    public function getPhotoLastChanged() : ?\PSX\DateTime\LocalDateTime
    {
        return $this->photoLastChanged;
    }
    public function setLastChanged(?\PSX\DateTime\LocalDateTime $lastChanged) : void
    {
        $this->lastChanged = $lastChanged;
    }
    public function getLastChanged() : ?\PSX\DateTime\LocalDateTime
    {
        return $this->lastChanged;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('name', $this->name);
        $record->put('party', $this->party);
        $record->put('bioUrl', $this->bioUrl);
        $record->put('state', $this->state);
        $record->put('constituency', $this->constituency);
        $record->put('elected', $this->elected);
        $record->put('photo', $this->photo);
        $record->put('photoLarge', $this->photoLarge);
        $record->put('photoLastChanged', $this->photoLastChanged);
        $record->put('lastChanged', $this->lastChanged);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
