<?php
/**
 * BundesratTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\UnknownStatusCodeException;
use Sdkgen\Client\TagAbstract;

class BundesratTag extends TagAbstract
{
    public function member(): BundesratMemberTag
    {
        return new BundesratMemberTag(
            $this->httpClient,
            $this->parser
        );
    }


}
