<?php
/**
 * CityCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

/**
 * @extends Collection<City>
 */
class CityCollection extends Collection
{
}
