<?php
/**
 * City automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class City implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?int $id = null;
    protected ?string $state = null;
    protected ?string $rb = null;
    protected ?string $district = null;
    protected ?string $verb = null;
    protected ?string $gem = null;
    protected ?string $name = null;
    protected ?string $zipCode = null;
    protected ?int $area = null;
    public function setId(?int $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setState(?string $state): void
    {
        $this->state = $state;
    }
    public function getState(): ?string
    {
        return $this->state;
    }
    public function setRb(?string $rb): void
    {
        $this->rb = $rb;
    }
    public function getRb(): ?string
    {
        return $this->rb;
    }
    public function setDistrict(?string $district): void
    {
        $this->district = $district;
    }
    public function getDistrict(): ?string
    {
        return $this->district;
    }
    public function setVerb(?string $verb): void
    {
        $this->verb = $verb;
    }
    public function getVerb(): ?string
    {
        return $this->verb;
    }
    public function setGem(?string $gem): void
    {
        $this->gem = $gem;
    }
    public function getGem(): ?string
    {
        return $this->gem;
    }
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setZipCode(?string $zipCode): void
    {
        $this->zipCode = $zipCode;
    }
    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }
    public function setArea(?int $area): void
    {
        $this->area = $area;
    }
    public function getArea(): ?int
    {
        return $this->area;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('state', $this->state);
        $record->put('rb', $this->rb);
        $record->put('district', $this->district);
        $record->put('verb', $this->verb);
        $record->put('gem', $this->gem);
        $record->put('name', $this->name);
        $record->put('zipCode', $this->zipCode);
        $record->put('area', $this->area);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
