<?php
/**
 * DistrictCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

/**
 * @extends Collection<District>
 */
class DistrictCollection extends Collection
{
}
