<?php
/**
 * District automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

class District implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $id = null;
    protected ?string $state = null;
    protected ?string $type = null;
    protected ?string $name = null;
    #[Key('nuts3')]
    #[Description('NUTS3 classification')]
    protected ?string $nuts = null;
    #[Description('Size of the area in km2')]
    protected ?int $area = null;
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setState(?string $state): void
    {
        $this->state = $state;
    }
    public function getState(): ?string
    {
        return $this->state;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setNuts(?string $nuts): void
    {
        $this->nuts = $nuts;
    }
    public function getNuts(): ?string
    {
        return $this->nuts;
    }
    public function setArea(?int $area): void
    {
        $this->area = $area;
    }
    public function getArea(): ?int
    {
        return $this->area;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('state', $this->state);
        $record->put('type', $this->type);
        $record->put('name', $this->name);
        $record->put('nuts3', $this->nuts);
        $record->put('area', $this->area);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
