<?php
/**
 * HospitalCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

/**
 * @extends Collection<Hospital>
 */
class HospitalCollection extends Collection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
