<?php
/**
 * Job automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class Job implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $job = null;
    protected ?string $title = null;
    protected ?string $number = null;
    protected ?JobLocation $location = null;
    protected ?string $employer = null;
    protected ?\PSX\DateTime\LocalDateTime $publishDate = null;
    protected ?\PSX\DateTime\LocalDateTime $entranceDate = null;
    public function setJob(?string $job) : void
    {
        $this->job = $job;
    }
    public function getJob() : ?string
    {
        return $this->job;
    }
    public function setTitle(?string $title) : void
    {
        $this->title = $title;
    }
    public function getTitle() : ?string
    {
        return $this->title;
    }
    public function setNumber(?string $number) : void
    {
        $this->number = $number;
    }
    public function getNumber() : ?string
    {
        return $this->number;
    }
    public function setLocation(?JobLocation $location) : void
    {
        $this->location = $location;
    }
    public function getLocation() : ?JobLocation
    {
        return $this->location;
    }
    public function setEmployer(?string $employer) : void
    {
        $this->employer = $employer;
    }
    public function getEmployer() : ?string
    {
        return $this->employer;
    }
    public function setPublishDate(?\PSX\DateTime\LocalDateTime $publishDate) : void
    {
        $this->publishDate = $publishDate;
    }
    public function getPublishDate() : ?\PSX\DateTime\LocalDateTime
    {
        return $this->publishDate;
    }
    public function setEntranceDate(?\PSX\DateTime\LocalDateTime $entranceDate) : void
    {
        $this->entranceDate = $entranceDate;
    }
    public function getEntranceDate() : ?\PSX\DateTime\LocalDateTime
    {
        return $this->entranceDate;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('job', $this->job);
        $record->put('title', $this->title);
        $record->put('number', $this->number);
        $record->put('location', $this->location);
        $record->put('employer', $this->employer);
        $record->put('publishDate', $this->publishDate);
        $record->put('entranceDate', $this->entranceDate);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
