<?php
/**
 * JobCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

/**
 * @extends Collection<Job>
 */
class JobCollection extends Collection
{
}
