<?php
/**
 * JobLocation automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class JobLocation implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $zip = null;
    protected ?string $place = null;
    protected ?string $state = null;
    protected ?string $country = null;
    protected ?JobCoordinate $coordinate = null;
    public function setZip(?string $zip): void
    {
        $this->zip = $zip;
    }
    public function getZip(): ?string
    {
        return $this->zip;
    }
    public function setPlace(?string $place): void
    {
        $this->place = $place;
    }
    public function getPlace(): ?string
    {
        return $this->place;
    }
    public function setState(?string $state): void
    {
        $this->state = $state;
    }
    public function getState(): ?string
    {
        return $this->state;
    }
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }
    public function getCountry(): ?string
    {
        return $this->country;
    }
    public function setCoordinate(?JobCoordinate $coordinate): void
    {
        $this->coordinate = $coordinate;
    }
    public function getCoordinate(): ?JobCoordinate
    {
        return $this->coordinate;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('zip', $this->zip);
        $record->put('place', $this->place);
        $record->put('state', $this->state);
        $record->put('country', $this->country);
        $record->put('coordinate', $this->coordinate);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
