<?php
/**
 * JobTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\Payload;
use Sdkgen\Client\Exception\UnknownStatusCodeException;
use Sdkgen\Client\TagAbstract;

class JobTag extends TagAbstract
{
    /**
     * Returns all available jobs
     *
     * @param int|null $page
     * @param string|null $search
     * @param string|null $location
     * @param string|null $employer
     * @return JobCollection
     * @throws ResponseException
     * @throws ClientException
     */
    public function getAll(?int $page = null, ?string $search = null, ?string $location = null, ?string $employer = null): JobCollection
    {
        $url = $this->parser->url('/job', [
        ]);

        $options = [
            'headers' => [
            ],
            'query' => $this->parser->query([
                'page' => $page,
                'search' => $search,
                'location' => $location,
                'employer' => $employer,
            ], [
            ]),
        ];

        try {
            $response = $this->httpClient->request('GET', $url, $options);
            $body = $response->getBody();

            $data = $this->parser->parse((string) $body, \PSX\Schema\SchemaSource::fromClass(JobCollection::class));

            return $data;
        } catch (ClientException $e) {
            throw $e;
        } catch (BadResponseException $e) {
            $body = $e->getResponse()->getBody();
            $statusCode = $e->getResponse()->getStatusCode();

            if ($statusCode === 400) {
                $data = $this->parser->parse((string) $body, \PSX\Schema\SchemaSource::fromClass(Response::class));

                throw new ResponseException($data);
            }

            if ($statusCode === 404) {
                $data = $this->parser->parse((string) $body, \PSX\Schema\SchemaSource::fromClass(Response::class));

                throw new ResponseException($data);
            }

            if ($statusCode === 500) {
                $data = $this->parser->parse((string) $body, \PSX\Schema\SchemaSource::fromClass(Response::class));

                throw new ResponseException($data);
            }

            throw new UnknownStatusCodeException('The server returned an unknown status code: ' . $statusCode);
        } catch (\Throwable $e) {
            throw new ClientException('An unknown error occurred: ' . $e->getMessage());
        }
    }



}
