<?php
/**
 * NewsCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

/**
 * @extends Collection<News>
 */
class NewsCollection extends Collection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
