<?php
/**
 * ResponseException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

use Sdkgen\Client\Exception\KnownStatusCodeException;

class ResponseException extends KnownStatusCodeException
{
    private Response $payload;

    public function __construct(Response $payload)
    {
        parent::__construct('The server returned an error');

        $this->payload = $payload;
    }

    /**
     * @return Response
     */
    public function getPayload(): Response
    {
        return $this->payload;
    }
}
