<?php
/**
 * StateCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

/**
 * @extends Collection<State>
 */
class StateCollection extends Collection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
