<?php
/**
 * SystemAboutApps automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;

/**
 * @extends \PSX\Record\Record<string>
 */
class SystemAboutApps extends \PSX\Record\Record
{
}
