<?php
/**
 * Warning automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class Warning implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $id = null;
    protected ?string $severity = null;
    protected ?string $urgency = null;
    protected ?string $type = null;
    protected ?string $title = null;
    protected ?\PSX\DateTime\LocalDateTime $startDate = null;
    protected ?\PSX\DateTime\LocalDateTime $expiresDate = null;
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setSeverity(?string $severity): void
    {
        $this->severity = $severity;
    }
    public function getSeverity(): ?string
    {
        return $this->severity;
    }
    public function setUrgency(?string $urgency): void
    {
        $this->urgency = $urgency;
    }
    public function getUrgency(): ?string
    {
        return $this->urgency;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }
    public function getTitle(): ?string
    {
        return $this->title;
    }
    public function setStartDate(?\PSX\DateTime\LocalDateTime $startDate): void
    {
        $this->startDate = $startDate;
    }
    public function getStartDate(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->startDate;
    }
    public function setExpiresDate(?\PSX\DateTime\LocalDateTime $expiresDate): void
    {
        $this->expiresDate = $expiresDate;
    }
    public function getExpiresDate(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->expiresDate;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('severity', $this->severity);
        $record->put('urgency', $this->urgency);
        $record->put('type', $this->type);
        $record->put('title', $this->title);
        $record->put('startDate', $this->startDate);
        $record->put('expiresDate', $this->expiresDate);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
