<?php
/**
 * WarningCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace DeutschlandAPI\SDK;


class WarningCollection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<Warning>|null
     */
    protected ?array $entries = null;
    /**
     * @param array<Warning>|null $entries
     */
    public function setEntries(?array $entries): void
    {
        $this->entries = $entries;
    }
    /**
     * @return array<Warning>|null
     */
    public function getEntries(): ?array
    {
        return $this->entries;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('entries', $this->entries);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
